### ISSUE TITLE
Create `1.0` release

### ISSUE THREAD

**Issue by tyler36** [tyler36/ddev-laravel-queue#14]
This issue is a placeholder/reminder.

#11  disables the "install from release" to clear up the workflow logs.

Confirm that all tests are enabled (currently 3 tests)

**Comment by rfay** [comment]
I see that the automated tests are currently failing. I'm working on a script to look at all add-ons and maybe other things to make sure we know when tests are failing.

**Comment by tyler36** [comment]
Yes, looking at the logs its the "install from release" test that is failing ...

```
# ddev get /home/runner/work/ddev-laravel-queue/ddev-laravel-queue/tests/.. with project test-laravel-queue in /home/runner/tmp/test-laravel-queue (/home/runner/tmp/test-laravel-queue)
ok 1 install from directory
# ddev get tyler36/ddev-laravel-worker with project test-laravel-queue in /home/runner/tmp/test-laravel-queue (/home/runner/tmp/test-laravel-queue)
not ok 2 install from release
```

#11 is probably the way we'll move forward and it's tests are passing (with the "install from release" test disabled.)
